yml - take 21

diff --git a/.github/workflows/man_b2s-api.yml b/.github/workflows/man_b2s-api.yml
--- a/.github/workflows/man_b2s-api.yml
+++ b/.github/workflows/man_b2s-api.yml
@@ -69,22 +69,23 @@ jobs:
           clientSecret=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')
           tenantId=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.tenantId')
 
-          if [ -z "$clientId" ]; then
-            echo "ClientId missing in AZURE_CREDENTIALS"
-          fi
-          if [ -z "$clientSecret" ]; then
-            echo "ClientSecret missing in AZURE_CREDENTIALS"
-          fi
-          if [ -z "$tenantId" ]; then
-            echo "TenantId missing in AZURE_CREDENTIALS"
-          fi
-
           if [ -z "$clientId" ] || [ -z "$clientSecret" ] || [ -z "$tenantId" ]; then
             echo "One or more required fields (clientId, clientSecret, tenantId) are missing in AZURE_CREDENTIALS."
             exit 1
           fi
 
           az login --service-principal -u "$clientId" -p "$clientSecret" --tenant "$tenantId"
+
+      # Verify and set the Azure Subscription
+      - name: Set Azure Subscription
+        run: |
+          subscriptionId=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.subscriptionId')
+          if [ -z "$subscriptionId" ]; then
+            echo "Subscription ID is missing in AZURE_CREDENTIALS."
+            exit 1
+          fi
+          az account set --subscription "$subscriptionId"
+          echo "Set the subscription to $subscriptionId."
 
       # Deploy to Azure Web App
       - name: Deploy to Azure Web App
